# Official Motia Dockerfile generated by: npx motia docker setup
# Modified for Railway deployment with Python steps
FROM motiadev/motia:latest

WORKDIR /app

# Install ALL Dependencies (need dev deps for TypeScript build)
COPY package*.json ./
RUN npm ci

# Copy Python requirements and install
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Move application files
COPY . .

# Setup Python steps dependencies (REQUIRED for Python steps)
RUN npx motia@latest install

# Build for production
RUN npx motia build

# Railway injects PORT, default to 3000 for local testing
ENV PORT=3000
ENV NODE_ENV=production
EXPOSE 3000

# Run using npm start which calls 'motia start'
# Railway will inject PORT automatically
CMD ["sh", "-c", "npx motia start -p $PORT -H 0.0.0.0"]
