/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'LogGreeting': EventHandler<{ requestId: string; greeting: string; processedBy: string }, never>
    'HelloAPI': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { message: string; status: string; appName: string }>, { topic: 'process-greeting'; data: { timestamp: string; appName: string; greetingPrefix: string; requestId: string } }>
    'NormalizeJob': EventHandler<{ source: 'arbeitnow' | 'hackernews' | 'reddit'; rawJob: Record<string, unknown> }, { topic: 'index-job'; data: { job: { id: string; title: string; company: string; location?: string; remote: boolean; url: string; description: string; source: 'arbeitnow' | 'hackernews' | 'reddit'; postedAt: string; fetchedAt: string; tags: Array<string>; healthScore: number } } }>
    'IndexJob': EventHandler<{ job: { id: string; title: string; company: string; location?: string; remote: boolean; url: string; description: string; source: 'arbeitnow' | 'hackernews' | 'reddit'; postedAt: string; fetchedAt: string; tags: Array<string>; healthScore: number } }, never>
    'FetchArbeitnow': EventHandler<{ source: string; manual?: boolean }, { topic: 'normalize-job'; data: { source: 'arbeitnow' | 'hackernews' | 'reddit'; rawJob: Record<string, unknown> } }>
    'RefreshAllSources': CronHandler<{ topic: 'fetch-jobs-trigger'; data: { source: string; manual?: boolean } }>
    'RefreshSource': ApiRouteHandler<Record<string, unknown>, ApiResponse<202, { message: string; source: string }> | ApiResponse<400, { error: string }>, { topic: 'fetch-jobs-trigger'; data: { source: string; manual?: boolean } }>
    'HealthCheck': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { status: string; timestamp: string; version: string }>, never>
    'GetSources': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { sources: Array<{ name: string; lastFetch: string | unknown; jobCount: number; status: 'success' | 'error' | 'pending' | 'unknown'; error?: string }> }>, never>
    'GetJobs': ApiRouteHandler<Record<string, unknown>, ApiResponse<200, { jobs: Array<{ id: string; title: string; company: string; location?: string; remote: boolean; url: string; description: string; source: 'arbeitnow' | 'hackernews' | 'reddit'; postedAt: string; fetchedAt: string; tags: Array<string>; healthScore: number }>; total: number; sources: Array<string>; lastUpdated: string }>, never>
    'ProcessGreeting': EventHandler<{ timestamp: string; appName: string; greetingPrefix: string; requestId: string }, { topic: 'greeting-processed'; data: { requestId: string; greeting: string; processedBy: string } }>
    'FetchHackerNews': EventHandler<{ source: string; manual?: boolean }, { topic: 'normalize-job'; data: { source: 'arbeitnow' | 'hackernews' | 'reddit'; rawJob: Record<string, unknown> } }>
  }
    
}