/**
 * Interview Questions for Career Compass AI Interview Flow
 *
 * These questions help understand user preferences beyond what's in the resume.
 * Used in Phase 4 of the Career Advisor integration.
 *
 * In Phase 7+, questions are dynamically generated by LLM based on resume content.
 * The static questions below serve as fallbacks when LLM is unavailable.
 */

export type InterviewCategory =
  | 'COMPENSATION'
  | 'LOCATION'
  | 'CULTURE'
  | 'COMPANY_STAGE'
  | 'TECHNICAL'

export interface InterviewQuestion {
  id: string
  question: string
  category: InterviewCategory
  placeholder: string
  helpText?: string
}

export interface InterviewAnswers {
  [questionId: string]: string
}

/**
 * Category display information for badges and styling
 */
export const CATEGORY_STYLES: Record<InterviewCategory, { label: string; bgColor: string; textColor: string }> = {
  COMPENSATION: {
    label: 'Compensation',
    bgColor: 'bg-green-600',
    textColor: 'text-green-100',
  },
  LOCATION: {
    label: 'Location',
    bgColor: 'bg-blue-600',
    textColor: 'text-blue-100',
  },
  CULTURE: {
    label: 'Culture',
    bgColor: 'bg-purple-600',
    textColor: 'text-purple-100',
  },
  COMPANY_STAGE: {
    label: 'Company Stage',
    bgColor: 'bg-yellow-600',
    textColor: 'text-yellow-100',
  },
  TECHNICAL: {
    label: 'Technical',
    bgColor: 'bg-indigo-600',
    textColor: 'text-indigo-100',
  },
}

/**
 * Default/fallback interview questions covering 5 key categories.
 * These are used when:
 * - LLM API is unavailable
 * - LLM generation fails
 * - Resume text is too short for meaningful analysis
 *
 * Order matters - this is the sequence users will see them.
 */
export const INTERVIEW_QUESTIONS: InterviewQuestion[] = [
  {
    id: 'compensation',
    question: "What's your target compensation? Include your minimum acceptable base salary, ideal salary, and whether equity compensation is important to you.",
    category: 'COMPENSATION',
    placeholder: "E.g., Minimum $150k base, targeting $180k+. Equity is important for early-stage companies but less critical for established ones. Benefits priorities: good health insurance, 401k match, flexible PTO...",
    helpText: "Be specific about base salary range and benefits priorities",
  },
  {
    id: 'location',
    question: "What are your location and remote work preferences? Are there geographic restrictions?",
    category: 'LOCATION',
    placeholder: "E.g., Remote required, open to occasional travel (1-2 times per quarter). Must be US timezone-friendly. Would consider hybrid in SF Bay Area or NYC only...",
    helpText: "Consider timezone requirements and travel flexibility",
  },
  {
    id: 'culture',
    question: "What company culture characteristics are important to you? What are red flags you'd avoid?",
    category: 'CULTURE',
    placeholder: "E.g., Value async communication, flat hierarchy, psychological safety. Prefer companies with strong engineering culture and work-life balance. Red flags: mandatory RTO, excessive on-call, no growth budget...",
    helpText: "Think about leadership style, values, and deal-breakers",
  },
  {
    id: 'company_stage',
    question: "What company stage do you prefer? Early startup, growth-stage, or established enterprise?",
    category: 'COMPANY_STAGE',
    placeholder: "E.g., Prefer Series A-C growth stage companies (50-500 employees). Not interested in pre-seed/seed (too risky) or Fortune 500 (too slow). Okay with late-stage startups preparing for IPO...",
    helpText: "Consider job stability vs equity upside trade-offs",
  },
  {
    id: 'technical',
    question: "What technical requirements do you have? Which technologies are must-haves vs nice-to-haves?",
    category: 'TECHNICAL',
    placeholder: "E.g., Must: TypeScript, React, Node.js. Nice-to-have: Go, Kubernetes, GraphQL. Avoid: PHP, legacy Java, Windows-only environments. Interested in: AI/ML, distributed systems...",
    helpText: "Include languages, frameworks, and tools",
  },
]
